## Data source configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=pwd
## JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
## Eureka Config
spring.application.name=ms-products
eureka.client.service-url.defaultZone=${eureka_url:http://localhost:8761/eureka}
eureka.instance.preferIpAddress=true
eureka.instance.hostname=ms-products
server.port=8086

